/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 18 18:51:41 GMT 2018
 */

package com.uepb.tcc.racingcar.evosuite;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.uepb.tcc.racingcar.Corrida;
import com.uepb.tcc.racingcar.EntreOsMelhores;
import com.uepb.tcc.racingcar.Piloto;
import java.util.List;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

//@RunWith(EvoRunner.class) 
//@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true) 
public class EntreOsMelhores_ESTest extends EntreOsMelhores_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Corrida[] corridaArray0 = new Corrida[0];
      EntreOsMelhores entreOsMelhores0 = new EntreOsMelhores(corridaArray0);
      List<String> list0 = entreOsMelhores0.RankingsPiloto();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Corrida[] corridaArray0 = new Corrida[1];
      Piloto[] pilotoArray0 = new Piloto[4];
      Piloto piloto0 = new Piloto("", "");
      pilotoArray0[0] = piloto0;
      pilotoArray0[1] = piloto0;
      pilotoArray0[2] = pilotoArray0[0];
      Piloto piloto1 = new Piloto("", "!q)");
      pilotoArray0[3] = piloto1;
      Corrida corrida0 = new Corrida("", pilotoArray0);
      corridaArray0[0] = corrida0;
      EntreOsMelhores entreOsMelhores0 = new EntreOsMelhores(corridaArray0);
      // Undeclared exception!
      try { 
        entreOsMelhores0.resultadoDosPilotos();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 3
         //
         verifyException("com.uepb.tcc.racingcar.Corrida", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Corrida[] corridaArray0 = new Corrida[2];
      EntreOsMelhores entreOsMelhores0 = new EntreOsMelhores(corridaArray0);
      // Undeclared exception!
      try { 
        entreOsMelhores0.RankingsPiloto();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.uepb.tcc.racingcar.EntreOsMelhores", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Corrida[] corridaArray0 = new Corrida[2];
      Piloto[] pilotoArray0 = new Piloto[4];
      Piloto piloto0 = new Piloto("com.uepb.tcc.racingcar.Corrida", "com.uepb.tcc.racingcar.Corrida");
      pilotoArray0[0] = piloto0;
      pilotoArray0[1] = piloto0;
      pilotoArray0[2] = piloto0;
      Piloto piloto1 = new Piloto("AZ", ":1icrMeTprt2)R]xo");
      pilotoArray0[3] = piloto1;
      Corrida corrida0 = new Corrida("com.uepb.tcc.racingcar.Corrida", pilotoArray0);
      corridaArray0[0] = corrida0;
      EntreOsMelhores entreOsMelhores0 = new EntreOsMelhores(corridaArray0);
      // Undeclared exception!
      try { 
        entreOsMelhores0.RankingsPiloto();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 3
         //
         verifyException("com.uepb.tcc.racingcar.Corrida", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      EntreOsMelhores entreOsMelhores0 = null;
      try {
        entreOsMelhores0 = new EntreOsMelhores((Corrida[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Corrida[] corridaArray0 = new Corrida[1];
      Piloto[] pilotoArray0 = new Piloto[4];
      Piloto piloto0 = new Piloto("", "");
      pilotoArray0[0] = piloto0;
      pilotoArray0[1] = pilotoArray0[0];
      pilotoArray0[2] = pilotoArray0[1];
      pilotoArray0[3] = pilotoArray0[0];
      Corrida corrida0 = new Corrida("", pilotoArray0);
      corridaArray0[0] = corrida0;
      EntreOsMelhores entreOsMelhores0 = new EntreOsMelhores(corridaArray0);
      Map<String, Integer> map0 = entreOsMelhores0.resultadoDosPilotos();
      assertEquals(1, map0.size());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Corrida[] corridaArray0 = new Corrida[1];
      EntreOsMelhores entreOsMelhores0 = new EntreOsMelhores(corridaArray0);
      // Undeclared exception!
      try { 
        entreOsMelhores0.resultadoDosPilotos();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.uepb.tcc.racingcar.EntreOsMelhores", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Corrida[] corridaArray0 = new Corrida[0];
      EntreOsMelhores entreOsMelhores0 = new EntreOsMelhores(corridaArray0);
      Map<String, Integer> map0 = entreOsMelhores0.resultadoDosPilotos();
      assertTrue(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Piloto[] pilotoArray0 = new Piloto[2];
      Piloto piloto0 = new Piloto("", "");
      pilotoArray0[0] = piloto0;
      Piloto piloto1 = new Piloto("0kKlB0)*8osQYWDk", "");
      pilotoArray0[1] = piloto1;
      Corrida corrida0 = new Corrida("0kKlB0)*8osQYWDk", pilotoArray0);
      Corrida[] corridaArray0 = new Corrida[2];
      corridaArray0[0] = corrida0;
      corridaArray0[1] = corrida0;
      EntreOsMelhores entreOsMelhores0 = new EntreOsMelhores(corridaArray0);
      List<String> list0 = entreOsMelhores0.RankingsPiloto();
      assertEquals(2, list0.size());
  }
}
